# Generated by Django 2.2.28 on 2026-03-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('flag_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('regionmode', models.CharField(blank=True, max_length=32)),
                ('worldmode', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'flag',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('is_guest', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-score', 'username'],
            },
        ),
    ]
