# Generated by Django 2.2.28 on 2026-03-18 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('flag_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=120)),
                ('country_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 code (e.g., 'ua' for Ukraine)", max_length=2)),
                ('continent', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'flag',
                'ordering': ['flag_id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CountryAlias',
            fields=[
                ('alias_id', models.AutoField(primary_key=True, serialize=False)),
                ('alias_name', models.CharField(help_text='Alternative name for the country', max_length=120)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='flagd.Flag')),
            ],
            options={
                'db_table': 'country_alias',
                'ordering': ['flag', 'alias_name'],
                'unique_together': {('flag', 'alias_name')},
            },
        ),
    ]
